KW30-Servlety/src/pl/alx/InfoBean.java
package pl.alx;

import java.time.LocalTime;

public class InfoBean {
	
	private String tekst = "Ala ma kota";

	public String getTekst() {
		return tekst;
	}

	public void setTekst(String tekst) {
		this.tekst = tekst;
	}
	
	public String getAktualnyCzas() {
		return LocalTime.now().toString();
	}
}

KW30-Servlety/WebContent/przyklad.jsp
<!-- komentarz html -->
<%-- komentarz JSP --%>
<%-- to poniżej to dyrektywa --%>
<%@page import="java.time.LocalTime"%>
<%@ page language="java" contentType="text/html; charset=utf-8"
    pageEncoding="utf-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title>Przykład JSP</title>
	</head>
	<body>
		<h1>Pierwszy plik JSP</h1>
		<p>Ala ma kota</p>
		
		<%-- scriptlet --%>
		|||<%
			System.out.println("Test ze skryptletu");
			out.println("kot ma kompilator");
		%>|||
		

		<%
			String tekst = "Zosia ma psa";
		%>		
		
		<%= tekst %>
		
		<%= "Ola ma " + "konia" %>
		
		
		<p>
			Teraz jest: <%= LocalTime.now() %>
		</p>
	</body>
</html>

KW30-Servlety/WebContent/przyklad2.jsp
<%@page import="java.time.LocalTime"%>
<%@ page language="java" contentType="text/html; charset=utf-8"
    pageEncoding="utf-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Insert title here</title>
</head>
<body>

	<% int sekunda = LocalTime.now().getSecond(); %>

	<p>Bieżąca sekunda: <%= sekunda %></p>

	<% if (sekunda % 2 == 0) { %>
		<p>sekunda parzysta</p>
	<% } else { %>
		<p>sekunda nieparzysta</p>
	<% } %>
	
	
	<%-- Expression Language (EL) --%>
	<p>Wynik: ${2+3}</p>
	
</body>
</html>

KW30-Servlety/WebContent/przyklad3.jsp
<%@ page language="java" contentType="text/html; charset=utf-8"
    pageEncoding="utf-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>EJB</title>
</head>
<body>

	<h1>EJB</h1>
	<%-- to jest akcja JSP --%>
	<jsp:useBean id="info" class="pl.alx.InfoBean"></jsp:useBean>

	<%--                          info.getTekst() --%>
	<p>Napis odczytany z beana: ${info.tekst}</p>

	<%-- uruchomi się metoda setTekst() --%>
	<jsp:setProperty property="tekst" name="info" value="Kot ma kompilator"/>
	<p>Napis odczytany z beana: ${info.tekst}</p>
	
	<%-- uruchomi się metoda getAktualnyCzas() --%>
	<p>Aktualny czas: ${info.aktualnyCzas}</p> 
	
	<%-- to nie zadziała, bo nie ma settera do aktualnyCzas w InfoBean --%>
	<%--<jsp:setProperty property="aktualnyCzas" name="info" value="16:06:06"/>  --%>
	
	
	
</body>
</html>

KW30-Servlety/WebContent/todo.jsp
<%@ page language="java" contentType="text/html; charset=utf-8"
    pageEncoding="utf-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Lista TODO</title>
</head>
<body>

	<h1>Lista TODO</h1>
	
	<h2>Co masz zrobić?</h2>
	
	<form method="post" action="todo-save">
		<input type="text" name="todo_item" placeholder="Pozycja do zapisania" />
		<input type="submit" value="Dodaj" />
	</form>
	
	<hr/>
	
	<h2>Twoja lista TODO</h2>
	
	<c:choose>
		<c:when test="${not empty todo_list}">
			<ul>
				<c:forEach var="todo_item" items="${todo_list}">
					<li>${todo_item}</li>
				</c:forEach>
			</ul>
		</c:when>
		<c:otherwise>
			<p>Strasznie tu pusto! Dodaj cos!</p>
		</c:otherwise>
	</c:choose>
	
	
	
	
</body>
</html>
 